# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ACEAPP' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ACEAPP
pod 'Firebase/Core'
pod 'Firebase/Database'

pod 'FirebaseUI/Auth'

pod 'FirebaseUI/Email'
pod 'FirebaseUI/Google'
pod 'FirebaseUI/Facebook'
pod 'FirebaseUI/Twitter'
pod 'FirebaseUI/Phone'

  target 'ACEAPPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ACEAPPUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

