# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ace Club' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ace Club

	pod 'Firebase/Core'
	pod 'Firebase/Database'

  target 'Ace ClubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Ace ClubUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
